#!/usr/bin/env bash
# subdomain pinpoints
subdomain=(www lb-01 web-01 web-02)
if [ "$#" -eq 1 ]
then
    for i in "${subdomain[@]}"
    do
	dig "$i"."$1" | grep -A1 'ANSWER SECTION:' | tail -n1 |
	awk -vsubd="$i" '{print "The subdomain " subd " is a " $4 " record and points to " $5}'
    done
else
    dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -n1 |
    awk -vsubd="$2" '{print "The subdomain " subd " is a " $4 " record and points to " $5}'
fi
