#!/usr/bin/env bash
# Displays "Holberton Shool" 10 times on the 9th iter displays "Hi"

i=1
while [ $i -le 10 ]
do
	echo "Holberton School"
	if [ "$i" == 9 ]
	then
		echo "Hi"
	fi
	i=$(( i + 1 ))
done
