#!/usr/bin/env bash
# 4th pos "Bad luck" 8th pos "Good luck" the rest "Holberton School"

i=0
while [ $i -le 10 ]
do
    if [ "$i" == 3 ]
    then
	echo "bad luck"
    elif [ "$i" == 7 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    i=$(( i + 1 ))
done
